# Generated by Django 5.2.5 on 2025-08-27 04:46

import django.db.models.deletion
import jugadores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=50)),
                ('numero_de_camiseta', models.IntegerField(blank=True, null=True)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('equipo', models.ForeignKey(default=jugadores.models.get_default_equipo_id, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugadores.equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('marcador_local', models.IntegerField(blank=True, null=True)),
                ('marcador_visitante', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('proximo', 'Próximo'), ('jugado', 'Jugado')], default='proximo', max_length=20)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='jugadores.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='jugadores.equipo')),
                ('jugador_partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_destacado', to='jugadores.jugador')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='jugadores.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('tarjetas_amarillas', models.IntegerField(default=0)),
                ('tarjetas_rojas', models.IntegerField(default=0)),
                ('amonestados', models.ManyToManyField(blank=True, related_name='amonestados_partidos', to='jugadores.jugador')),
                ('anotadores', models.ManyToManyField(blank=True, related_name='goles_partidos', to='jugadores.jugador')),
                ('asistentes', models.ManyToManyField(blank=True, related_name='asistencias_partidos', to='jugadores.jugador')),
                ('expulsados', models.ManyToManyField(blank=True, related_name='expulsados_partidos', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.partido')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='jugadores.torneo'),
        ),

        migrations.CreateModel(
            name='VotacionJugadorPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='jugadores.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
