# Generated by Django 5.2.5 on 2025-08-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
