# Generated by Django 5.2.5 on 2025-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
