# Generated by Django 5.2.5 on 2025-08-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_jugador_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='username',
        ),
    ]
