# Generated by Django 5.2.5 on 2025-10-09 14:02

import django.db.models.deletion
import jugadores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_remove_jugador_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='torneos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='jugadores.torneo', verbose_name='torneos'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='amonestados',
            field=models.ManyToManyField(blank=True, related_name='amonestados_partidos', to='jugadores.jugador', verbose_name='amonestados'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='anotadores',
            field=models.ManyToManyField(blank=True, related_name='goles_partidos', to='jugadores.jugador', verbose_name='anotadores'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='asistencias',
            field=models.IntegerField(default=0, verbose_name='asistencias'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='asistencias_partidos', to='jugadores.jugador', verbose_name='asistentes'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='expulsados',
            field=models.ManyToManyField(blank=True, related_name='expulsados_partidos', to='jugadores.jugador', verbose_name='expulsados'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='goles',
            field=models.IntegerField(default=0, verbose_name='goles'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.partido', verbose_name='partido'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='tarjetas_amarillas',
            field=models.IntegerField(default=0, verbose_name='tarjetas amarillas'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='tarjetas_rojas',
            field=models.IntegerField(default=0, verbose_name='tarjetas rojas'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(default=jugadores.models.get_default_equipo_id, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugadores.equipo', verbose_name='equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero_de_camiseta',
            field=models.IntegerField(blank=True, null=True, verbose_name='número de camiseta'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(max_length=50, verbose_name='posición'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='jugadores.equipo', verbose_name='equipo local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='jugadores.equipo', verbose_name='equipo visitante'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('jugado', 'Jugado')], default='proximo', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugador_partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_destacado', to='jugadores.jugador', verbose_name='jugador destacado'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='marcador_local',
            field=models.IntegerField(blank=True, null=True, verbose_name='marcador local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='marcador_visitante',
            field=models.IntegerField(blank=True, null=True, verbose_name='marcador visitante'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='jugadores.torneo', verbose_name='torneo'),
        ),
        migrations.AlterField(
            model_name='votacionjugadorpartido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='votacionjugadorpartido',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.jugador', verbose_name='jugador'),
        ),
        migrations.AlterField(
            model_name='votacionjugadorpartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='jugadores.partido', verbose_name='partido'),
        ),
        migrations.AlterField(
            model_name='votacionjugadorpartido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscripcion', 'Inscripción'), ('arbitraje', 'Arbitraje'), ('tarjetas', 'Tarjetas')], max_length=20, verbose_name='tipo de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='monto')),
                ('metodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='método de pago')),
                ('referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='jugadores.jugador', verbose_name='jugador')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
