# Generated by Django 5.2.5 on 2025-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_equipo_logo_alter_equipo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('otro', 'Otro')], default='transferencia', max_length=50, verbose_name='método de pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(default='', max_length=200, verbose_name='referencia'),
            preserve_default=False,
        ),
    ]
