# Generated by Django 5.2.5 on 2025-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0006_pago_comprobante_alter_pago_metodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo/Divisas'), ('paypal', 'PayPal'), ('otro', 'Otro')], max_length=50, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('inscripcion', 'Inscripción'), ('arbitraje', 'Arbitraje'), ('tarjetas_amarilla', 'Tarjeta Amarilla'), ('tarjetas_roja', 'Tarjeta Roja'), ('otro', 'Otro')], max_length=20, verbose_name='tipo de pago'),
        ),
    ]
