# Generated by Django 5.2.5 on 2025-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0007_alter_pago_metodo_alter_pago_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (Bs)'), ('USD', 'Dólares (USD)')], default='VES', max_length=3, verbose_name='moneda'),
        ),
    ]
