# Generated by Django 5.2.5 on 2025-10-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_pago_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Amarilla'), ('roja', 'Roja')], max_length=10, verbose_name='tipo')),
                ('minuto', models.IntegerField(blank=True, null=True, verbose_name='minuto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='jugadores.jugador', verbose_name='jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='jugadores.partido', verbose_name='partido')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
    ]
