# Generated by Django 5.2.5 on 2025-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0009_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='anulada',
            field=models.BooleanField(default=False, verbose_name='anulada'),
        ),
    ]
