# Generated by Django 5.2.5 on 2025-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0011_tarjeta_motivo_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='motivo rechazo'),
        ),
    ]
