# Generated by Django 5.2.5 on 2025-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0012_pago_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='referencia'),
        ),
    ]
