# Generated by Django 5.2.5 on 2025-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0013_alter_pago_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo/Divisas'), ('otro', 'Otro')], max_length=50, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='referencia'),
        ),
    ]
