# Generated by Django 5.2.5 on 2025-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0015_add_pago_archivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='archivado',
            field=models.BooleanField(default=False, verbose_name='archivado'),
        ),
    ]
