# Generated by Django 5.2.5 on 2025-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0016_alter_pago_archivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='referencia'),
        ),
    ]
