# Generated by Django 5.2.5 on 2025-10-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0019_alter_jugador_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
