# Generated by Django 5.2.5 on 2025-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0020_jugador_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='descripción'),
        ),
    ]
