# Generated by Django 5.2.5 on 2025-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0021_pago_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='edad'),
        ),
    ]
