# Generated by Django 5.2.5 on 2025-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0022_jugador_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
