# Generated by Django 5.2.5 on 2025-10-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0024_equipo_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='foto_de_perfil',
        ),
    ]
